/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brazedblue_intervox_serial_MacSerialDriver */

#ifndef _Included_com_brazedblue_intervox_serial_MacSerialDriver
#define _Included_com_brazedblue_intervox_serial_MacSerialDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef com_brazedblue_intervox_serial_MacSerialDriver_kBufferSize
#define com_brazedblue_intervox_serial_MacSerialDriver_kBufferSize 10280L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud300
#define com_brazedblue_intervox_serial_MacSerialDriver_baud300 380L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud600
#define com_brazedblue_intervox_serial_MacSerialDriver_baud600 189L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud1200
#define com_brazedblue_intervox_serial_MacSerialDriver_baud1200 94L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud1800
#define com_brazedblue_intervox_serial_MacSerialDriver_baud1800 62L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud2400
#define com_brazedblue_intervox_serial_MacSerialDriver_baud2400 46L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud3600
#define com_brazedblue_intervox_serial_MacSerialDriver_baud3600 30L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud4800
#define com_brazedblue_intervox_serial_MacSerialDriver_baud4800 22L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud7200
#define com_brazedblue_intervox_serial_MacSerialDriver_baud7200 14L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud9600
#define com_brazedblue_intervox_serial_MacSerialDriver_baud9600 10L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud14400
#define com_brazedblue_intervox_serial_MacSerialDriver_baud14400 6L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud19200
#define com_brazedblue_intervox_serial_MacSerialDriver_baud19200 4L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud28800
#define com_brazedblue_intervox_serial_MacSerialDriver_baud28800 2L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud38400
#define com_brazedblue_intervox_serial_MacSerialDriver_baud38400 1L
#undef com_brazedblue_intervox_serial_MacSerialDriver_baud57600
#define com_brazedblue_intervox_serial_MacSerialDriver_baud57600 0L
#undef com_brazedblue_intervox_serial_MacSerialDriver_stop10
#define com_brazedblue_intervox_serial_MacSerialDriver_stop10 16384L
#undef com_brazedblue_intervox_serial_MacSerialDriver_stop15
#define com_brazedblue_intervox_serial_MacSerialDriver_stop15 -32768L
#undef com_brazedblue_intervox_serial_MacSerialDriver_stop20
#define com_brazedblue_intervox_serial_MacSerialDriver_stop20 -16384L
#undef com_brazedblue_intervox_serial_MacSerialDriver_noParity
#define com_brazedblue_intervox_serial_MacSerialDriver_noParity 0L
#undef com_brazedblue_intervox_serial_MacSerialDriver_oddParity
#define com_brazedblue_intervox_serial_MacSerialDriver_oddParity 4096L
#undef com_brazedblue_intervox_serial_MacSerialDriver_evenParity
#define com_brazedblue_intervox_serial_MacSerialDriver_evenParity 12288L
#undef com_brazedblue_intervox_serial_MacSerialDriver_data5
#define com_brazedblue_intervox_serial_MacSerialDriver_data5 0L
#undef com_brazedblue_intervox_serial_MacSerialDriver_data6
#define com_brazedblue_intervox_serial_MacSerialDriver_data6 2048L
#undef com_brazedblue_intervox_serial_MacSerialDriver_data7
#define com_brazedblue_intervox_serial_MacSerialDriver_data7 1024L
#undef com_brazedblue_intervox_serial_MacSerialDriver_data8
#define com_brazedblue_intervox_serial_MacSerialDriver_data8 3072L
/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    SerGetBuf
 * Signature: (S[I)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_SerGetBuf
  (JNIEnv *, jclass, jshort, jintArray);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    SerReset
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_SerReset
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    SerSetBuf
 * Signature: (SIS)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_SerSetBuf
  (JNIEnv *, jclass, jshort, jint, jshort);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    NewPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_NewPtr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    DisposePtr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_DisposePtr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    OpenDriver
 * Signature: ([B[S)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_OpenDriver
  (JNIEnv *, jclass, jbyteArray, jshortArray);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    CloseDriver
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_CloseDriver
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    FSWrite
 * Signature: (S[I[B)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_FSWrite
  (JNIEnv *, jclass, jshort, jintArray, jbyteArray);

/*
 * Class:     com_brazedblue_intervox_serial_MacSerialDriver
 * Method:    FSRead
 * Signature: (S[I[B)S
 */
JNIEXPORT jshort JNICALL Java_com_brazedblue_intervox_serial_MacSerialDriver_FSRead
  (JNIEnv *, jclass, jshort, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
