/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brazedblue_intervox_view3D_OpenGLJNI */

#ifndef _Included_com_brazedblue_intervox_view3D_OpenGLJNI
#define _Included_com_brazedblue_intervox_view3D_OpenGLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pRemoveAllGeometriesFromView
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pRemoveAllGeometriesFromView
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pRemoveGeometryFromView
 * Signature: (JJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pRemoveGeometryFromView
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pViewHasGeometry
 * Signature: (JJ[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pViewHasGeometry
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pAddGeometryToView
 * Signature: (JJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pAddGeometryToView
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pDebugSetOpenGLLighting
 * Signature: (J[[F[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pDebugSetOpenGLLighting
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pDebugGetOpenGLLighting
 * Signature: (J[[F[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pDebugGetOpenGLLighting
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetZoomFocus
 * Signature: (IIJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetZoomFocus
  (JNIEnv *, jobject, jint, jint, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pGetGLPixelData
 * Signature: (J[III[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pGetGLPixelData
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pDispose3DGeometry
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pDispose3DGeometry
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pGetGeometryResolution
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pGetGeometryResolution
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pCreateGLContext
 * Signature: ([I[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pCreateGLContext
  (JNIEnv *, jobject, jintArray, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pDisposeGLContext
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pDisposeGLContext
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetRotation
 * Signature: (J[F[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetRotation
  (JNIEnv *, jobject, jlong, jfloatArray, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pDebugCheckDeallocation
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pDebugCheckDeallocation
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pCreateGeometryFromRegion
 * Signature: (II[[BIJI[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pCreateGeometryFromRegion
  (JNIEnv *, jobject, jint, jint, jobjectArray, jint, jlong, jint, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pCreateGeometryFromVersion
 * Signature: (JJ[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pCreateGeometryFromVersion
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pZoomContext
 * Signature: (FJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pZoomContext
  (JNIEnv *, jobject, jfloat, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pAbsoluteZoomContext
 * Signature: (FJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pAbsoluteZoomContext
  (JNIEnv *, jobject, jfloat, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetFiducials
 * Signature: ([[F[Ljava/lang/String;J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetFiducials
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetShowsFiducials
 * Signature: (ZJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetShowsFiducials
  (JNIEnv *, jobject, jboolean, jlong, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetGeometryColor
 * Signature: (JFFF[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetGeometryColor
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetGeometryTransparency
 * Signature: (JF[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetGeometryTransparency
  (JNIEnv *, jobject, jlong, jfloat, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetLowResView
 * Signature: (JZ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetLowResView
  (JNIEnv *, jobject, jlong, jboolean, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetPointerLocation
 * Signature: (J[F[F[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetPointerLocation
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pShowPointer
 * Signature: (JZ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pShowPointer
  (JNIEnv *, jobject, jlong, jboolean, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pGLUTInit
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pGLUTInit
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_brazedblue_intervox_view3D_OpenGLJNI
 * Method:    pSetDebugging
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_brazedblue_intervox_view3D_OpenGLJNI_pSetDebugging
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
